import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { variables } from './tokens.mjs'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const generateCss = () => {
  const themeVars = Object.entries(variables)
    .map(([key, value]) => {
      const cssValue = Array.isArray(value) ? value.join(', ') : value
      return `  --${key}: ${cssValue};`
    })
    .join('\n')

  return `
/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * This file is generated automatically from tokens.mjs during the Astro build.
 * Any direct modifications will be overwritten.
 */

@theme {
${themeVars}
}
`
}

const outputPath = path.resolve(__dirname, 'tokens.generated.css')
await fs.writeFile(outputPath, generateCss())
